name: ZeusGateway
version: '1.0-SNAPSHOT'
main: org.vennv.zeusGatewayLegacy.ZeusGatewayLegacy
description: Zeus Anti-Cheat data collector plugin - legacy Gateway artifact foundation
authors:
  - VennDev
